OBJECTS=VTableFix.o 

%.elf:				VTableFix.o
VTableFix.o:		VTableFix.cpp
VTableFix.cpp:		*.o
	@echo "// This file is automatically generated" > VTableFix.cpp
	@echo "#include <tap.h>" >> VTableFix.cpp
	@echo "#include <vtable.h>" >> VTableFix.cpp
	@echo "" >> VTableFix.cpp
	nm $^ | grep -o -G 'D _vt.*' | sed 's/D \(.*\)/extern vtable \1;/g' >> VTableFix.cpp
	@echo "" >> VTableFix.cpp
	@echo "void FixupVTables()" >> VTableFix.cpp
	@echo "{" >> VTableFix.cpp
	@nm $^ | grep -o -G 'D _vt.*' | sed 's/D \(.*\)/\tFixupVTable( \1 );/g' >> VTableFix.cpp
	@echo "}" >> VTableFix.cpp
