VTABLEFIX=VTableFix.o 

# use the template repository mechanism built into gcc if USE_FREPO is defined
# this may give slightly smaller executables, slightly longer build times
# and should make template class vtables global symbols, so you can use
# virtual functions in templates. Any unforseen problems - comment out the 
# next line and things will go back to the old template = big macro mode
#USE_FREPO=1

ifdef USE_FREPO

MANDATORY_CXX_FLAGS+=-frepo
TEMPLATESBUILTFLAG=buildtemplates.done

REPOLINKOPTS=-Xlinker --defsym -Xlinker FixupVTables__Fv=0 -Xlinker --defsym -Xlinker TAP_Main=0 -Xlinker --defsym -Xlinker TAP_EventHandler=0

BUILDTEMPLATES=[ -e $@ ] || ( echo "Building Template Instantiations..." ; $(CXX) -nostdlib $(CXXFLAGS) $(OBJECTS) $(LDFLAGS) -o $@ $(REPOLINKOPTS) 2>&1 | grep recompiling | tee /tmp/template.out ; [ -s /tmp/template.out ] || (echo "Template build complete." ;touch $@) )

$(TEMPLATESBUILTFLAG) : $(OBJECTS) $(LIBRARIES)
	rm -f $@
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@$(BUILDTEMPLATES) 
	@[ -e $@ ] || (echo "Not all templates instantiated." ; false)

endif

	
prelink.elf: $(OBJECTS) $(LIBRARIES) $(TEMPLATESBUILTFLAG)
	$(LD) $(OBJECTS) $(LDFLAGS) -o $@ --defsym FixupVTables__Fv=0

VTableFix.o:		VTableFix.cpp

VTableFix.cpp:		prelink.elf
	@echo "// This file is automatically generated" > VTableFix.cpp
	@echo "#include <tap.h>" >> VTableFix.cpp
	@echo "#include <vtable.h>" >> VTableFix.cpp
	@echo "" >> VTableFix.cpp
	nm $^ | grep -o -G 'D _vt.*' | sed 's/D \(.*\)/extern vtable \1;/g' >> VTableFix.cpp
	nm $^ | grep -o -G 'd _vt.*' | sed 's/d \(.*\)/#error "Local vtable \1 cannot be fixed - all classes with virtual functions must be global (declared in a .h, defined in a .cpp)"/g' >> VTableFix.cpp
	@echo "" >> VTableFix.cpp
	@echo "void FixupVTables()" >> VTableFix.cpp
	@echo "{" >> VTableFix.cpp
	@nm $^ | grep -o -G 'D _vt.*' | sed 's/D \(.*\)/\tFixupVTable( \1 );/g' >> VTableFix.cpp
	@echo "}" >> VTableFix.cpp
