//
//	  MultiViewEPG jim16 Tue 1 Apr 12:12:00
//
//	  Copyright (C) 2008 Jim16
//
//	  This is free software; you can redistribute it and/or modify
//	  it under the terms of the GNU General Public License as published by
//	  the Free Software Foundation; either version 2 of the License, or
//	  (at your option) any later version.
//
//	  The software is distributed in the hope that it will be useful,
//	  but WITHOUT ANY WARRANTY; without even the implied warranty of
//	  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//	  GNU General Public License for more details.
//
//	  You should have received a copy of the GNU General Public License
//	  along with this software; if not, write to the Free Software
//	  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

// Firebird Library Functions WOW!
#include "libFirebird/libFireBird.h"
#include "libFirebird/main/InitTAPex.c"
#include "libFirebird/main/EMMA_DGRP_OSD.c"
#include "libFirebird/main/GetFWInfo.c"
#include "libFirebird/main/CallFirmware.c"
#include "libFirebird/main/Log.c"
#include "libFirebird/main/isMasterpiece.c"
#include "libFirebird/main/FindInstructionSequence.c"
#include "libFirebird/main/LoadFirmwareDat.c"
#include "libFirebird/flash/FlashInitialize.c"
#include "libFirebird/flash/TimeFormat.c"
#include "libFirebird/flash/TimeDiff.c"
#include "libFirebird/flash/Now.c"
#include "libFirebird/flash/AddTime.c"
#include "libFirebird/flash/GetEEPROMAddress.c"
#include "libFirebird/av/InitAudioPointers.c"
#include "libFirebird/av/isAnyOSDVisible.c"
#include "libFirebird/av/ShowMessageWindow.c"
#include "libFirebird/av/ShowMessageWin.c"
#include "libFirebird/av/EndMessageWin.c"
#include "libFirebird/tapapifix/tapapifix.c"
#include "libFirebird/rec/HDD_DecodeRECHeader.c"
#include "libFirebird/rec/HDD_EncodeRECHeader.c"
#include "libFirebird/rec/HDD_isRecording.c"
#include "libFirebird/rec/HDD_isAnyRecording.c"
#include "libFirebird/rec/getRECSlotAddress.c"
#include "libFirebird/rec/HDD_RECSlotSetDuration.c"
#include "libFirebird/tap/HDD_TAP_GetIndexByID.c"
#include "libFirebird/tap/HDD_TAP_isRunning.c"
#include "libFirebird/tap/HDD_TAP_GetIDByFileName.c"
#include "libFirebird/tap/HDD_TAP_GetInfo.c"
#include "libFirebird/tap/HDD_TAP_Start.c"
#include "libFirebird/tap/HDD_TAP_DisabledEventHandler.c"
#include "libFirebird/tap/HDD_TAP_isDisabled.c"
#include "libFirebird/tap/HDD_TAP_Disable.c"
#include "libFirebird/tap/HDD_TAP_GetIDByIndex.c"
#include "libFirebird/tap/HDD_TAP_DisableAll.c"
#include "libFirebird/hdd/ChangeDirRoot.c"
#include "libFirebird/hdd/HDD_ChangeDir.c"
#include "libFirebird/hdd/HDD_Move.c"
#include "libFirebird/tap/HDD_TAP_PushDir.c"
#include "libFirebird/tap/HDD_TAP_PopDir.c"
#include "libFirebird/tap/HDD_TAP_GetCurrentDirCluster.c"
#include "libFirebird/tap/HDD_TAP_SetCurrentDirCluster.c"
#include "libFirebird/string/isLegalChar.c"
#include "libFirebird/string/MakeValidFileName.c"
//#include "libFirebird/ini/INICloseFile.c"
//#include "libFirebird/ini/INIFindStartEnd.c"
//#include "libFirebird/ini/INIGetARGB.c"
//#include "libFirebird/ini/INIGetHexByte.c"
//#include "libFirebird/ini/INIGetHexDWord.c"
//#include "libFirebird/ini/INIGetHexWord.c"
//#include "libFirebird/ini/INIGetInt.c"
//#include "libFirebird/ini/INIGetString.c"
//#include "libFirebird/ini/INIKillKey.c"
//#include "libFirebird/ini/INIOpenFile.c"
//#include "libFirebird/ini/INISaveFile.c"
//#include "libFirebird/ini/INISetARGB.c"
//#include "libFirebird/ini/INISetComment.c"
//#include "libFirebird/ini/INISetHexByte.c"
//#include "libFirebird/ini/INISetHexDWord.c"
//#include "libFirebird/ini/INISetHexWord.c"
//#include "libFirebird/ini/INISetInt.c"
//#include "libFirebird/ini/INISetString.c"
//#include "libFirebird/ini/LangGetString.c"
//#include "libFirebird/ini/LangLoadStrings.c"
//#include "libFirebird/ini/LangUnloadStrings.c"
#include "libFirebird/ini/INILocateFile.c"
#include "libFirebird/hdd/HDD_TruncateFile.c"
#include "libFirebird/hdd/HDD_TouchFile.c"
#include "libFirebird/hdd/HDD_GetClusterSize.c"
#include "libFirebird/hdd/HDD_SetFileDateTime.c"
#include "libFirebird/hdd/HDD_ReadSectorDMA.c"
#include "libFirebird/string/stricstr.c"
#include "libFirebird/string/RTrim.c"
#include "libFirebird/imem/IMEM_Init.c"
#include "libFirebird/imem/IMEM_isInitialized.c"
#include "libFirebird/imem/IMEM_Kill.c"
#include "libFirebird/imem/IMEM_Alloc.c"
#include "libFirebird/imem/IMEM_Free.c"
#include "libFirebird/imem/IMEM_GetInfo.c"
#include "libFirebird/imem/IMEM_Compact.c"
#include "libFirebird/imem/compact.c"
#include "libFirebird/InstructionSequences/FIS_GetGP.c"
#include "libFirebird/InstructionSequences/FIS_fwBIOS.c"
#include "libFirebird/InstructionSequences/FIS_vTAPTable.c"
#include "libFirebird/InstructionSequences/FIS_vFlash.c"
#include "libFirebird/InstructionSequences/FIS_vWD1.c"
#include "libFirebird/InstructionSequences/FIS_vEEPROM.c"
#include "libFirebird/InstructionSequences/FIS_vRECSlotAddress.c"
#include "libFirebird/InstructionSequences/FIS_fwTAPStart.c"
#include "libFirebird/InstructionSequences/FIS_fwMoveOld.c"
#include "libFirebird/InstructionSequences/FIS_fwEnqueueEvent.c"
#include "libFirebird/fwpatches/PatchApply.c"
#include "libFirebird/fwpatches/PatchCleanList.c"
#include "libFirebird/fwpatches/PatchFindNextListEntry.c"
#include "libFirebird/fwpatches/PatchFindType.c"
#include "libFirebird/fwpatches/PatchGetInstalled.c"
#include "libFirebird/fwpatches/PatchInstallID.c"
#include "libFirebird/fwpatches/PatchIsInstalled.c"
#include "libFirebird/fwpatches/PatchLoadModule.c"
#include "libFirebird/fwpatches/PatchReinstallList.c"
#include "libFirebird/fwpatches/PatchRemoveID.c"
#include "libFirebird/fwpatches/PatchUnloadModule.c"

